### PR TITLE
Update videostream to 2.3.0

### PR DESCRIPTION
**Pull request by yciabaud**
I was waiting for a greenkeeper PR to update videostream but it does seems to be enabled on this repo.
My concern is about the preload issues a was facing issue (jhiesey/videostream#22)

### CODE REVIEW

**Comment by feross** [comment]
If you freshly install `render-media`, you get 2.3.0. That's how semver and the `^` operator work.

Greenkeeper is enabled, but it only sends a PR if:
- `videostream` updates to a version that is included in our semver range, AND that update breaks our tests. This is so we can fix it.
- Or, `videostream` releases a new major version (not included in our semver range). This is so we can stay up to date.

**Comment by feross** [comment]
That said, there's no harm in merging this.

**Comment by yciabaud** [comment]
Oh that's right, sorry for the noise.

**Comment by feross** [comment]
No problem :)

**Pull request merged**
