### PR TITLE
update videostream

### PR DESCRIPTION
**Pull request by tzarebczan**
Recently 2 bugs were fixed:
https://github.com/jhiesey/videostream/issues/38
https://github.com/jhiesey/videostream/issues/42

### CODE REVIEW

**Comment by tzarebczan** [comment]
@feross tagging for awareness, thanks!

**Comment by feross** [comment]
The way that semver works, the new version will be used automatically. You can read about "Tilde & Caret Shorthand" here: https://nodesource.com/blog/semver-a-primer/

But this doesn't hurt, so I'll merge.

**Review by feross — APPROVED** [review]

**Comment by tzarebczan** [comment]
Ah, forgot about that, will get our yarn lock file updated! Thanks again.

**Comment by feross** [comment]
Released as 3.1.3.

**Pull request merged**
